export const Users = [
    {
        id:1,
        profilePicture: "https://avatars.githubusercontent.com/u/1420371?v=4",
        username: "Landon Conover",
    },
    {
        id:2,
        profilePicture: "https://avatars.githubusercontent.com/u/4356894?v=4",
        username: "Thor Anderson",
    },
    {
        id:3,
        profilePicture: "https://avatars.githubusercontent.com/u/7151837?v=4",
        username: "Paul Cheney",
    },
    {
        id:4,
        profilePicture: "https://avatars.githubusercontent.com/u/71342671?v=4",
        username: "Andrew Peterson",
    },
    {
        id:5,
        profilePicture: "https://images.pexels.com/photos/1310522/pexels-photo-1310522.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        username: "Danila Lubov",
    },
    {
        id:6,
        profilePicture: "https://avatars.githubusercontent.com/u/49534559?v=4",
        username: "Raine Petersen",
    },
    {
        id:7,
        profilePicture: "https://avatars.githubusercontent.com/u/71342567?v=4",
        username: "Moe Peterson",
    },
    {
        id:8,
        profilePicture: "https://images.pexels.com/photos/943084/pexels-photo-943084.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        username: "Lavina Paige",
    },
    {
        id:9,
        profilePicture: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        username: "Echo Crawford",
    },
    {
        id:10,
        profilePicture: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        username: "Zilla Bowie",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "I am currently traveling in San Diego right now and my hotel has a gym. This reminded me how coding is like going to the gym. You can't look or code like me if you don't follow this philosophy.",
        photo: "assets/body-builder.jpg",
        date: "Just now",
        userId: 1,
        likes: 0,
        comments: 0,
    },
    {
        id: 2,
        desc: "Visiting my Viking ancestors' stomping grounds in Norway.",
        photo: "https://images.pexels.com/photos/1562058/pexels-photo-1562058.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        date: "10 mins ago",
        userId: 2,
        likes: 13,
        comments: 5,
    },
    {
        id: 3,
        desc: "Beauty of being a web developer is that I get to code anywhere I want. Today I am in New Zealand!",
        photo: "https://images.pexels.com/photos/221011/pexels-photo-221011.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        date: "30 mins ago",
        userId: 3,
        likes: 13,
        comments: 5,
    },
    {
        id: 4,
        desc: "Found some cheap plane tickets to Japan. Order yours before they're gone at: https://www.expedia.com/Destinations-In-Japan.d89.Flight-Destinations",
        photo: "https://images.pexels.com/photos/4606721/pexels-photo-4606721.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        date: "45 mins ago",
        userId: 4,
        likes: 13,
        comments: 5,
    },
    {
        id: 5,
        desc: "Was feeling like a weak coder today, then I realized my life philosophy of coding is like going to the gym and then I realized that I am freakin' jacked!",
        photo: "https://preview.redd.it/znoc0r5dcwr51.jpg?auto=webp&s=8f5201ba6687b11bed85092a12c594395e3bf7ef",
        date: "6 hours ago",
        userId: 1,
        likes: 420,
        comments: 69,
    },
    {
        id: 6,
        desc: "Venic Italy is exactly what the doctor ordered!",
        photo: "https://images.pexels.com/photos/208701/pexels-photo-208701.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        date: "1 hour ago",
        userId: 5,
        likes: 29,
        comments:16,
    },
    {
        id: 7,
        desc: "Taking a well deserved vacation away from coding for awhile.",
        photo: "https://images.pexels.com/photos/1583770/pexels-photo-1583770.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        date: "2 hours ago",
        userId: 6,
        likes: 69,
        comments: 9,
    },
    {
        id: 8,
        desc: "Made a new app! Check it out on my Github.",
        photo: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
        date: "3 hours ago",
        userId: 7,
        likes: 13,
        comments: 5,
    },
    {
        id: 9,
        desc: "At the Dicke Wirtin pub in Charlottenburg, Germany. The perfect meal to enjoy after a successful day of coding.",
        photo: "https://images.pexels.com/photos/53628/pexels-photo-53628.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        date: "4 hours ago",
        userId: 8,
        likes: 13,
        comments: 5,
    },
    {
        id: 10,
        desc: "I learned the coolest trick in VS code today. To edit multiple lines of code at the same time, highlight text and then press crtl + f2.",
        photo: "https://code.visualstudio.com/assets/images/code-stable.png",
        date: "5 hours ago",
        userId: 9,
        likes: 17,
        comments: 6,
    },
    {
        id: 11,
        desc: "There are more places to go in China besides the Great Wall.",
        photo: "https://images.pexels.com/photos/235648/pexels-photo-235648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        date: "6 hours ago",
        userId: 10,
        likes: 13,
        comments: 5,
    },
    {
        id: 12,
        desc: "Some people ask me 'Lando, how do you code so fast?' The answer to that question:",
        photo: "https://cdn.shopify.com/s/files/1/1365/2497/articles/Screen_Shot_2018-03-16_at_7.38.07_AM_1024x1024.png?v=1521211527",
        date: "1 day ago",
        userId: 1,
        likes: 420,
        comments: 69,
    },
];